name: Release
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.label, 'mackerelio:release-v')
    steps:
      - name: Extract version tag from branch name
        id: extract-version
        run: |
          echo "::set-output name=version::${BRANCH#release-}"
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Add Release Tag
        run: |
          git tag ${{ steps.extract-version.outputs.version }}
      - name: Push Release Tag
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
